language: cpp

os: osx

osx_image: xcode12u

addons:
  sonarcloud:
    organization: "pocketpiglet-mobile-github"
    token:
      secure: "mXf9bOpibkgJ0EPK+NwyLgPeMDAUKbd9IOaSy6pmHtaNU0JySTudU8A4ZRfeJr8TM7oT30p8Lq/oaue9zOoEW1UaGY2DkfaisDZ3roHcRzpGPL+nKJygbRVh50y7E+62aXOj3VG8J0/RTrfTAD6b09Dma+3puAjuX9LUJvuLfmDJIKvaVVPJwLTO1k+RsqcvFsOPracwF5/PFnHeRzCkiJ6YZgKBAt6HJwX59WWGu7dZkHHhLisuNRU1yVHf734RbiZMuLgmHg31Im0MWBe2s+UiYUDQQCGu1sl2LeblaJ6SIjJNk5+S6OOrK/Nkasu9qbt2gFCZizFRLI2B1wjIUpo2sd3Qomox6eFSJ4zdtDdOVQoHrdrWj6KMPY6ijyLqZVKUTFkv5R/KPJZbuYQy6dESnesQp4jqoaouGcgQQwUQAFqijibBr8T6+JjzbOUuu7A/aO38yRzqq/RI1Lmm29LHnYL5sIaNNqFmFDRbNb+pzOWhmbCiz7sBW8qN4Xk3bHOQaeis6Z+zQdmUoRHNV0sJHPnuvDPudtnr5HXemeD8dRaE0DgCSlJy3TJUX9rJ6brUGeojU2Yo2+lLeyeq/+TLQ1Q4JoBWoX17g5iUOWa7GjNaI1StlXLbNGLPbvSmmexmeL2oUB0EIUrYPTYVtFqVdS+Lxc9GETbIssQE9yA="

install:
  - |
    echo && \
    echo "---- INSTALLATION OF HOMEBREW PACKAGES ----" && \
    echo && \
    brew install p7zip && \
    echo && \
    echo "------- INSTALLATION OF QT PACKAGES -------" && \
    echo && \
    bash tools/install-qt.sh --version 5.12.9 --target ios --toolchain ios --directory "$HOME/Qt" qtbase qtdeclarative qtquickcontrols2 qtmultimedia qtsensors qtpurchasing && \
    echo && \
    echo "----------- END OF INSTALLATION -----------" && \
    echo

script:
  - |
    echo && \
    echo "---------- ENVIRONMENT VARIABLES ----------" && \
    echo && \
    export PATH="$HOME/Qt/5.12.9/ios/bin:$PATH" && \
    export QMAKE_CFLAGS_ENV="-Werror" && \
    export QMAKE_CXXFLAGS_ENV="-Werror" && \
    export QMAKE_OBJECTIVE_CFLAGS_ENV="-Werror" && \
    echo && \
    echo "--------- UNSHALLOW GIT FOR SONAR ---------" && \
    echo && \
    git fetch --unshallow && \
    echo && \
    echo "---------- CREATE BUILD DIRECTORY ---------" && \
    echo && \
    mkdir .build && \
    cd .build && \
    echo && \
    echo "------------------ QMAKE ------------------" && \
    echo && \
    qmake ../pocketpiglet.pro && \
    echo && \
    echo "------------------ MAKE -------------------" && \
    echo && \
    make XCODEBUILD_FLAGS="CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO" debug-device && \
    echo && \
    echo "----------- XCODEBUILD ANALYZE ------------" && \
    echo && \
    xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CLANG_ANALYZER_OUTPUT=text -scheme pocketpiglet -configuration Debug -sdk iphoneos analyze | tee .analyze-output.txt && \
    [[ "$(grep ": warning:" .analyze-output.txt)" == "" ]] && \
    [[ "$(grep ": note:" .analyze-output.txt)" == "" ]] && \
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then \
        echo && \
        echo "------------- MAKE DISTCLEAN --------------" && \
        echo && \
        make distclean && \
        echo && \
        echo "------------------ QMAKE ------------------" && \
        echo && \
        qmake ../pocketpiglet.pro && \
        echo && \
        echo "-------------- SONAR WRAPPER --------------" && \
        echo && \
        build-wrapper-macosx-x86 --out-dir bw-output make XCODEBUILD_FLAGS="CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO" debug-device && \
        echo && \
        echo "-------------- SONAR SCANNER --------------" && \
        echo && \
        cd .. && \
        sonar-scanner -Dsonar.projectKey=pocketpiglet-mobile_pocketpiglet-ios \
                      -Dsonar.projectName="PocketPiglet iOS" \
                      -Dsonar.sources=. \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.exclusions="qml_*.cpp,qrc_*.cpp,3rdparty/**/*,ios/frameworks/**/*,qml/**/*,translations/*" \
                      -Dsonar.cfamily.build-wrapper-output=.build/bw-output \
                      -Dsonar.cfamily.cache.enabled=false \
                      -Dsonar.cfamily.threads=1 \
                      -Dsonar.cpp.file.suffixes=.cpp,.mm; \
    fi
