name: "Build"

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

  schedule:
  - cron: "0 10 * * 6"

jobs:
  build:
    name: "Build"
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    env:
      QT_VERSION: 5.12.11

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Install additional packages"
      run: |
        bash tools/install-qt.sh --version "$QT_VERSION" --target ios --toolchain ios --directory "$HOME/Qt" qtbase qtdeclarative qtquickcontrols2 qtmultimedia qtsensors qtpurchasing

    - name: "Run build"
      env:
        QMAKE_CFLAGS_ENV: "-Werror"
        QMAKE_CXXFLAGS_ENV: ""
        QMAKE_OBJECTIVE_CFLAGS_ENV: "-Werror"
      run: |
        export PATH="$HOME/Qt/$QT_VERSION/ios/bin:$PATH"
        mkdir .build
        cd .build
        qmake ../pocketpiglet.pro
        make XCODEBUILD_FLAGS="CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO -UseModernBuildSystem=NO" debug-device
